// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module("matrix", []);

  app.directive("matrix", function($compile) {
    return {
      scope: {
        rows: "=",
        cols: "=",
        cont: "=content"
      },
      restrict: "E",
      link: function(scope, element, attrs) {
        var createMatrix;
        createMatrix = function() {
          var d, d1, e, i, j, r, _i, _j, _ref, _ref1;
          element.empty();
          e = document.createElement("table");
          e.className = e.className + " matrix";
          for (j = _i = 0, _ref = parseInt(scope.rows) - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; j = 0 <= _ref ? ++_i : --_i) {
            r = document.createElement("tr");
            for (i = _j = 0, _ref1 = parseInt(scope.cols) - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
              d1 = angular.element("<td></td>");
              d1.addClass("{{cont[" + (j * scope.rows + i) + "]}}");
              d = $compile(d1)(scope);
              angular.element(r).append(d);
            }
            angular.element(e).append(r);
          }
          return element.prepend(e);
        };
        scope.$watch("rows", function() {
          return createMatrix();
        });
        return scope.$watch("cols", function() {
          return createMatrix();
        });
      }
    };
  });

}).call(this);
